development:
  adapter: postgresql
  encoding: utf8
  database: local_puding_app
  host: localhost
  pool: 5
  username: myapp
  password: password1

# test:
#   adapter: postgresql
#   encoding: utf8
#   database: local_test_puding_app
#   host: localhost
#   pool: 5
#   username: myapp
#   password: password1

production:
  adapter: postgresql
  encoding: utf8
  database: puding_app
  host: localhost
  pool: 5
  username: rails
  password: secret